# Generated by Django 5.0.7 on 2024-10-06 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('domain', models.CharField(choices=[('design', 'Design'), ('tech', 'Tech'), ('Innovation', 'Innovation')], max_length=100, null=True)),
                ('idea_description', models.TextField()),
                ('idea_ppt', models.FileField(null=True, upload_to='ppt/')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_person_name', models.CharField(max_length=100)),
                ('receipt_image', models.ImageField(null=True, upload_to='receipts/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.team')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='event.team')),
            ],
        ),
    ]
